/***********************************************
 * $author: javery
 * $date  : 27 mar 03 
 * $descp : routines to generate algebric surfaces
 * $path  : C:\Program Files\Microsoft Visual Studio\MyProjects\KaosDemoEngine\alg_surf.h
 * $ver   : 0.0.0
 ***********************************************/

#ifndef __ALG_SURF_H__
#define __ALG_SURF_H__ 

#include "vector.h"
#include "model.h"

void AS_Sphere( pModel_t , int , int );

#endif