/***********************************************
 * $author: javery
 * $date  : 27 mar 03 
 * $descp : routines to generate algebric surfaces
 * $path  : C:\Program Files\Microsoft Visual Studio\MyProjects\KaosDemoEngine\alg_surf.h
 * $ver   : 0.0.0
 ***********************************************/

#include "alg_surf.h"

void AS_Sphere( pModel_t sphere , int radius , int percision )
{
	ENT_M_InitStandAlone( sphere );
	
	for( int index = 0;index < percision;index++ )
	{
		
		
		for( int in = 0;in < 3;in++ )
		{
			

		}


	}



}

